version: '2'
services:
  tuzigiri-db:
    build:
      context: ./infra/mysql
      args:
        MYSQL_ROOT_PASSWORD: "password"
        MIGRATOR_PASSWORD: "password"
        APP_USER_PASSWORD: "password"
    image: tuzigiri-db:latest
    container_name: tuzigiri-db
    ports:
      - "3306:3306"
    volumes:
      - ./infra/mysql/db:/var/lib/mysql
      - ./infra/mysql/log:/var/log/mysql
    environment:
      ENV: "local"
      TZ: "Asia/Tokyo"
  tuzigiri-app:
    build: .
    image: tuzigiri-app:latest
    container_name: tuzigiri-app
    ports:
      - "8080:8080"
    links:
      - tuzigiri-db
  tuzigiri-web:
    build: ./infra/nginx
    image: tuzigiri-web:latest
    container_name: tuzigiri-web
    ports:
      - "80:80"
    links:
      - tuzigiri-app
