version: '2'
services:
  tuzigiri-db:
    build:
      context: ./infra/mysql
      args:
        MYSQL_ROOT_PASSWORD: "password"
        MIGRATOR_PASSWORD: "password"
        APP_USER_PASSWORD: "password"
    image: tuzigiri-db:latest
    container_name: tuzigiri-db
    ports:
      - "3306:3306"
    volumes:
      - ./infra/mysql/db:/var/lib/mysql
      - ./infra/mysql/log:/var/log/mysql
    environment:
      ENV: "local"
      TZ: "Asia/Tokyo"
  tuzigiri-backend:
    build: .
    image: tuzigiri-backend:latest
    container_name: tuzigiri-backend
    ports:
      - "8080:8080"
  tuzigiri-frontend:
    build: ./frontend
    image: tuzigiri-frontend:latest
    container_name: tuzigiri-frontend
    environment:
      HOST: '0.0.0.0'
      PORT: 3000
    ports:
      - "3000:3000"
  tuzigiri-web:
    build: ./infra/nginx
    image: tuzigiri-web:latest
    container_name: tuzigiri-web
    volumes:
      - ./infra/nginx/log:/var/log/nginx
    ports:
      - "80:80"
